version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
  api:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis